---
# Tasks for installing Helm

- name: Set Helm version
  ansible.builtin.set_fact:
    helm_version: "{{ kubernetes_apps_helm_version | default('v3.14.3') }}"

- name: Check if Helm is already installed
  ansible.builtin.command: which helm
  register: helm_installed
  changed_when: false
  failed_when: false
  check_mode: false

# Handle check mode directly for temp directory
- name: Set dummy temp directory path for check mode
  ansible.builtin.set_fact:
    helm_temp_dir:
      path: '/tmp/helm_temp_check_mode'
  when: ansible_check_mode

- name: Download and install Helm if not installed
  when: helm_installed.rc != 0 and not ansible_check_mode
  block:
    - name: Create temporary directory for Helm installation
      ansible.builtin.tempfile:
        state: directory
        suffix: helm
      register: helm_temp_dir_result

    - name: Set temp directory fact
      ansible.builtin.set_fact:
        helm_temp_dir: '{{ helm_temp_dir_result }}'

    - name: Download Helm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: '{{ helm_temp_dir.path }}/get_helm.sh'
        mode: '0700'

    - name: Install Helm
      ansible.builtin.command: '{{ helm_temp_dir.path }}/get_helm.sh'
      environment:
        DESIRED_VERSION: '{{ helm_version }}'
      register: helm_installation
      changed_when: helm_installation.rc == 0

    - name: Clean up temporary files
      ansible.builtin.file:
        path: '{{ helm_temp_dir.path }}'
        state: absent
      when: helm_temp_dir.path is defined

# Skip actual helm commands in check mode
- name: Skip helm repo commands in check mode
  ansible.builtin.debug:
    msg: 'Skipping Helm repo commands in check mode'
  when: ansible_check_mode

# Only execute helm commands when not in check mode
- name: Add stable Helm repository
  ansible.builtin.command: helm repo add stable https://charts.helm.sh/stable
  register: helm_repo_add
  changed_when: helm_repo_add.rc == 0
  failed_when: false
  when: not ansible_check_mode

- name: Add bitnami Helm repository
  ansible.builtin.command: helm repo add bitnami https://charts.bitnami.com/bitnami
  register: helm_repo_add_bitnami
  changed_when: helm_repo_add_bitnami.rc == 0
  failed_when: false
  when: not ansible_check_mode

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  register: helm_repo_update
  changed_when: helm_repo_update.rc == 0
  when: not ansible_check_mode

- name: Verify Helm installation
  ansible.builtin.command: helm version --short
  register: helm_verify
  changed_when: false
  failed_when: helm_verify.rc != 0
  when: not ansible_check_mode

- name: Display Helm version
  ansible.builtin.debug:
    msg: "{{ 'Helm installed successfully: ' + helm_verify.stdout if not ansible_check_mode else 'Helm installation simulated in check mode' }}"
