---
# Defaults for k3s_master role

# Whether to copy kubeconfig to local machine
k3s_master_copy_kubeconfig_to_local: true

# Whether to enable HA mode
k3s_master_ha_mode: true

# Default TLS SANs for the API server
k3s_master_tls_san: '{{ ansible_default_ipv4.address }},{{ ansible_hostname }},{{ inventory_hostname }}'

# Keep these as globals since they're used across roles
k3s_version: v1.31.7+k3s1
k3s_channel: stable
