---
# Host-specific settings for the master/server node
node_labels:
  role: master
  environment: production
  node-type: control-plane

# Control plane node taint - allows system workloads but prevents regular workloads
node_taints:
  - 'node-role.kubernetes.io/control-plane:NoSchedule'

# System settings optimized for control plane operations
system_settings:
  vm.max_map_count: 262144
  fs.file-max: 65536
  net.core.somaxconn: 32768
  net.ipv4.ip_local_port_range: '1024 65535'
