---
# Variables for Debian-based systems

common_packages:
  - curl
  - wget
  - vim
  - iptables
  - ca-certificates
  - gnupg
  - apt-transport-https
  - python3
  - python3-pip
  - software-properties-common
  - lsb-release
  - jq

common_service_manager: systemd

common_networking_service:
  name: systemd-networkd
  enabled: true

common_firewall_package: ufw
