---
# Configure firewall settings for K3s nodes

- name: Check if firewalld is installed
  ansible.builtin.command: command -v firewalld
  register: firewalld_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: Configure firewalld if installed
  when: firewalld_check.rc == 0 and common_configure_firewall | default(true) | bool
  block:
    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow K3s required ports in firewalld
      ansible.posix.firewalld:
        port: '{{ item }}/tcp'
        permanent: true
        state: enabled
      loop: '{{ common_firewall_allowed_tcp_ports | default([22, 6443, 10250]) }}'
      notify: Reload firewalld

- name: Check if ufw is installed
  ansible.builtin.command: command -v ufw
  register: ufw_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: Configure ufw if installed
  when: ufw_check.rc == 0 and firewalld_check.rc != 0 and common_configure_firewall | default(true) | bool
  block:
    - name: Ensure ufw is installed
      ansible.builtin.package:
        name: ufw
        state: present

    - name: Allow K3s required ports in ufw
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop: '{{ common_firewall_allowed_tcp_ports | default([22, 6443, 10250]) }}'

    - name: Enable ufw
      community.general.ufw:
        state: enabled
        policy: deny
