---
# Common tasks for all nodes

- name: Include OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - 'default.yml'
      paths:
        - '{{ role_path }}/vars'
  tags: [always]

- name: Update package cache
  ansible.builtin.package:
    update_cache: yes
  tags: [packages]

- name: Install basic packages
  ansible.builtin.package:
    name: '{{ common_packages }}'
    state: present
  tags: [packages]

- name: Ensure pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install the kubernetes Python library
  ansible.builtin.pip:
    name: kubernetes
    state: present

- name: Disable swap
  ansible.builtin.include_tasks: disable_swap.yml
  tags: [system]

- name: Configure sysctl parameters
  ansible.builtin.include_tasks: sysctl.yml
  tags: [system]

- name: Configure host networking
  ansible.builtin.include_tasks: networking.yml
  tags: [networking]

- name: Configure firewall
  ansible.builtin.include_tasks: firewall.yml
  tags: [firewall]
  when: common_configure_firewall | default(true) | bool
