---
# Connection settings (common for all hosts)
ansible_user: sanjin
ansible_ssh_private_key_file: ~/.ssh/k3s_id_ed25519
ansible_python_interpreter: /usr/bin/python3.10

# System settings (common for all hosts)
timezone: 'Europe/Berlin'

# K3s cluster configuration
k3s_version: 'v1.31.7+k3s1'
k3s_token: 'K10bfc2044a4c8631eb83658b392948c60d0fc39b5e7425c59d47de9106bb5a68a8::server:71c3db22ed96a7e9a1d4d22d6a7e3844'

# Network and domain settings
cloudflare_domain: 'phizio.net'
cloudflare_email: 'admin@phizio.net'
metallb_addresses: '10.0.0.200-10.0.0.220'

# Component versions (centralized for easier updates)
cert_manager_version: 'v1.17.1'
traefik_version: 'v3.3.4'
longhorn_version: 'v1.8.1'
kube_prometheus_stack_version: '70.3.0'
rancher_version: '2.10.3'
