---
- name: Prepare all nodes
  hosts: k3s_cluster
  become: true
  vars_files:
    - '../group_vars/all.yml'
  roles:
    - common

- name: Setup K3s master
  hosts: master
  become: true
  vars_files:
    - '../group_vars/all.yml'
    - '../group_vars/master.yml'
    - '../group_vars/secure.yml'
  roles:
    - k3s_master

- name: Get master node token for workers
  hosts: master
  become: true
  tasks:
    - name: Get node token from master
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Set node token as a fact
      ansible.builtin.set_fact:
        k3s_node_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
        cacheable: yes

- name: Setup K3s workers
  hosts: workers
  become: true
  vars_files:
    - '../group_vars/all.yml'
    - '../group_vars/workers.yml'
  roles:
    - k3s_worker
