---
# Main tasks for k3s master nodes

- name: Create k3s directory
  ansible.builtin.file:
    path: '{{ k3s_server_location }}'
    state: directory
    mode: '0755'

- name: Check if cluster is already initialized
  ansible.builtin.stat:
    path: '{{ k3s_server_location }}/server/node-token'
  register: k3s_node_token
  when: inventory_hostname == groups['master'][0]

# First master installation
- name: Install K3s first master
  ansible.builtin.include_tasks: install_first_master.yml
  when:
    - inventory_hostname == groups['master'][0]
    - not k3s_node_token.stat.exists or k3s_node_token.stat.exists == false

# Additional masters installation
- name: Install K3s additional masters
  ansible.builtin.include_tasks: install_additional_masters.yml
  when:
    - inventory_hostname != groups['master'][0]
    - k3s_ha_mode | bool

- name: Get kubectl configuration
  ansible.builtin.include_tasks: kubectl_config.yml
  when: inventory_hostname == groups['master'][0]
