---
# Tasks for K3s worker nodes

- name: Get the master node token
  ansible.builtin.set_fact:
    k3s_node_token: "{{ hostvars[groups['master'][0]].k3s_node_token }}"

- name: Download K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install K3s agent
  ansible.builtin.command:
    cmd: >-
      INSTALL_K3S_VERSION={{ k3s_version }}
      INSTALL_K3S_CHANNEL={{ k3s_channel }}
      K3S_URL=https://{{ k3s_apiserver_host }}:{{ k3s_apiserver_port }}
      K3S_TOKEN={{ k3s_node_token }}
      /tmp/k3s-install.sh agent
      --node-ip {{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}
      {% for key, value in (k3s_node_labels | default({})).items() %}
      --node-label {{ key }}={{ value }}
      {% endfor %}
      {% for taint in (k3s_node_taints | default([])) %}
      --node-taint {{ taint }}
      {% endfor %}
  register: k3s_worker_install
  changed_when: k3s_worker_install.rc == 0
  failed_when: k3s_worker_install.rc != 0

- name: Verify K3s installation
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
    enabled: yes
